- search:
    provider: google
    target: _blank

- datetime:
    text_size: xl
    format:
      dateStyle: full
      timeStyle: short

- openmeteo:
    label: HomeAssistant Weather
    latitude: 37.7749
    longitude: -122.4194
    timezone: America/Los_Angeles
    units: imperial

- resources:
    cpu: true
    memory: true
    disk: /
