version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    rebase-strategy: "auto"
    insecure-external-code-execution: "deny"
    ignore:
      - dependency-name: "torch"
        update-types: ["version-update:semver-major"]
      - dependency-name: "tensorflow"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
