# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    allow:
      - dependency-type: "direct"
    insecure-external-code-execution: "deny"
    commit-message:
      prefix: "[SECURITY]"
    labels: ["dependencies","security"]
    rebase-strategy: auto
    open-pull-requests-limit: 10

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "[AUTO]"
    rebase-strategy: auto
    open-pull-requests-limit: 10

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "[SECURITY]"
    rebase-strategy: auto
    labels: ["ci","security"]

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: auto

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    rebase-strategy: auto
