packages:
  - apps/*
  - services/*
  - packages/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - aws-sdk
  - bcrypt
  - better-sqlite3
  - esbuild
  - msgpackr-extract
  - prisma
  - protobufjs
  - sharp
  - tesseract.js
  - unrs-resolver
