\
param(
  [ValidateSet('orchestrator','worker-rtx3060','worker-rtx3090ti','worker-rtx5090')]
  [string]$MachineRole = 'orchestrator',

  [int]$GiteaWebPort = 3100,
  [int]$GiteaSshPort = 2222,

  # If empty, we auto-set to http://<LAN-IP>:<port>/
  [string]$GiteaRootUrl = "",

  # If empty, we auto-set to the hostname part of GiteaRootUrl
  [string]$GiteaDomain = "",

  # If empty, we auto-set to GiteaDomain
  [string]$GiteaSshDomain = "",

  [switch]$EnableAIReviewer,
  [switch]$EnableActions,
  [switch]$EnablePublicTunnel,

  [switch]$Force
)

$ErrorActionPreference = "Stop"

function Log {
  param([string]$Msg, [ValidateSet("INFO","OK","WARN","ERR")] [string]$Level="INFO")
  $c = @{ INFO="Cyan"; OK="Green"; WARN="Yellow"; ERR="Red" }[$Level]
  $ts = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
  Write-Host "[$ts][$Level] $Msg" -ForegroundColor $c
}

function Require-Cmd($name, $hint) {
  try { & $name --version | Out-Null; Log "✅ $name found" "OK" }
  catch { throw "$name not found. $hint" }
}

function Get-LanIPv4 {
  # Prefer a non-loopback, non-APIPA IPv4
  $ips = Get-NetIPAddress -AddressFamily IPv4 -ErrorAction SilentlyContinue |
    Where-Object { $_.IPAddress -and $_.IPAddress -notlike "169.254.*" -and $_.IPAddress -ne "127.0.0.1" } |
    Sort-Object -Property PrefixOrigin, SuffixOrigin |
    Select-Object -ExpandProperty IPAddress
  if ($ips -and $ips.Count -gt 0) { return $ips[0] }
  return "127.0.0.1"
}

function New-RandomHex([int]$bytes) {
  $b = New-Object byte[] $bytes
  [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($b)
  return ([System.BitConverter]::ToString($b)).Replace("-", "").ToLower()
}

function Parse-EnvFile([string]$path) {
  $map = @{}
  if (-not (Test-Path $path)) { return $map }
  Get-Content $path | ForEach-Object {
    if ($_ -match '^\s*#') { return }
    if ($_ -match '^\s*$') { return }
    $kv = $_.Split('=',2)
    if ($kv.Count -eq 2) { $map[$kv[0].Trim()] = $kv[1] }
  }
  return $map
}

function Write-EnvFile([string]$path, [hashtable]$map) {
  $order = @(
    "NYRA_MACHINE","NYRA_NETWORK",
    "GITEA_ROOT_URL","GITEA_DOMAIN","GITEA_SSH_DOMAIN","GITEA_WEB_PORT","GITEA_SSH_PORT",
    "GITEA_DB_PASS",
    "GITEA_ADMIN_USER","GITEA_ADMIN_PASS","GITEA_ADMIN_EMAIL",
    "GITEA_TOKEN","GITEA_RUNNER_TOKEN","WEBHOOK_SECRET","WEBHOOK_AUTH_TOKEN",
    "OPENAI_BASE_URL","OPENROUTER_API_KEY",
    "REVIEW_MODEL","REVIEW_MAX_CHARS","REVIEW_POST_AS_REVIEW","REVIEW_LABEL",
    "GITEA_RUNNER_LABELS",
    "CLOUDFLARED_TUNNEL_TOKEN"
  )

  $lines = New-Object System.Collections.Generic.List[string]
  $lines.Add("# Generated by Setup-NYRA-Gitea.ps1 on $(Get-Date -Format 'yyyy-MM-dd HH:mm:ss')")
  $lines.Add("# Replace OPENROUTER_API_KEY only if you enable -EnableAIReviewer")
  $lines.Add("")
  foreach ($k in $order) {
    if ($map.ContainsKey($k)) { $lines.Add("$k=$($map[$k])") }
  }

  # preserve any extra keys
  foreach ($k in ($map.Keys | Sort-Object)) {
    if ($order -contains $k) { continue }
    $lines.Add("$k=$($map[$k])")
  }

  Set-Content -Path $path -Value ($lines -join "`n") -Encoding UTF8
}

function Ensure-DockerNetwork([string]$name) {
  $nets = & docker network ls --format "{{.Name}}" 2>$null
  if ($nets -notcontains $name) {
    Log "Creating docker network: $name" "INFO"
    & docker network create $name | Out-Null
    Log "✅ Network created: $name" "OK"
  } else {
    Log "✅ Network exists: $name" "OK"
  }
}

function Render-Template([string]$templatePath, [hashtable]$tokens) {
  $c = Get-Content $templatePath -Raw
  foreach ($k in $tokens.Keys) {
    $c = $c.Replace($k, $tokens[$k])
  }
  return $c
}

function Wait-Http([string]$url, [int]$seconds=180) {
  Log "Waiting for Gitea at $url ..." "INFO"
  $deadline = (Get-Date).AddSeconds($seconds)
  while ((Get-Date) -lt $deadline) {
    try {
      $r = Invoke-WebRequest -Uri $url -UseBasicParsing -TimeoutSec 3
      if ($r.StatusCode -ge 200 -and $r.StatusCode -lt 500) {
        Log "✅ Gitea is responding (HTTP $($r.StatusCode))" "OK"
        return
      }
    } catch { }
    Start-Sleep -Seconds 3
  }
  throw "Timed out waiting for Gitea to respond at $url"
}

function Docker-Exec([string]$container, [string[]]$cmd) {
  $full = @("exec", $container) + $cmd
  return & docker @full
}

# --- Preconditions
Require-Cmd "docker" "Install Docker Desktop, then reopen PowerShell."
try { & docker compose version | Out-Null; Log "✅ docker compose found" "OK" } catch { throw "docker compose not found. Update Docker Desktop." }

$here = $PSScriptRoot
$envPath = Join-Path $here ".env.gitea"

$existing = Parse-EnvFile $envPath
if ((Test-Path $envPath) -and -not $Force) {
  Log "Found existing .env.gitea (use -Force to regenerate missing fields)" "INFO"
}

$lanIp = Get-LanIPv4

# Compute URLs/domains
if (-not $GiteaRootUrl) { $GiteaRootUrl = "http://$lanIp`:$GiteaWebPort/" }
if (-not $GiteaDomain) {
  $u = [Uri]$GiteaRootUrl
  $GiteaDomain = $u.Host
}
if (-not $GiteaSshDomain) { $GiteaSshDomain = $GiteaDomain }

# Fill env map
$env = @{}
$env["NYRA_MACHINE"] = $MachineRole
$env["NYRA_NETWORK"] = $existing["NYRA_NETWORK"]; if (-not $env["NYRA_NETWORK"]) { $env["NYRA_NETWORK"] = "nyra-net" }

$env["GITEA_ROOT_URL"] = $GiteaRootUrl
$env["GITEA_DOMAIN"] = $GiteaDomain
$env["GITEA_SSH_DOMAIN"] = $GiteaSshDomain
$env["GITEA_WEB_PORT"] = "$GiteaWebPort"
$env["GITEA_SSH_PORT"] = "$GiteaSshPort"

# Secrets (generate if missing)
$env["GITEA_DB_PASS"] = $existing["GITEA_DB_PASS"]; if (-not $env["GITEA_DB_PASS"] -or $Force) { if (-not $env["GITEA_DB_PASS"]) { $env["GITEA_DB_PASS"] = New-RandomHex 24 } }
$env["GITEA_ADMIN_USER"] = $existing["GITEA_ADMIN_USER"]; if (-not $env["GITEA_ADMIN_USER"]) { $env["GITEA_ADMIN_USER"] = "apotheosis" }
$env["GITEA_ADMIN_EMAIL"] = $existing["GITEA_ADMIN_EMAIL"]; if (-not $env["GITEA_ADMIN_EMAIL"]) { $env["GITEA_ADMIN_EMAIL"] = "apotheosis@ratehunter.net" }
$env["GITEA_ADMIN_PASS"] = $existing["GITEA_ADMIN_PASS"]; if (-not $env["GITEA_ADMIN_PASS"] -or $Force) { if (-not $env["GITEA_ADMIN_PASS"]) { $env["GITEA_ADMIN_PASS"] = New-RandomHex 24 } }

$env["WEBHOOK_SECRET"] = $existing["WEBHOOK_SECRET"]; if (-not $env["WEBHOOK_SECRET"] -or $Force) { if (-not $env["WEBHOOK_SECRET"]) { $env["WEBHOOK_SECRET"] = New-RandomHex 32 } }
$env["WEBHOOK_AUTH_TOKEN"] = $existing["WEBHOOK_AUTH_TOKEN"]; if (-not $env["WEBHOOK_AUTH_TOKEN"] -or $Force) { if (-not $env["WEBHOOK_AUTH_TOKEN"]) { $env["WEBHOOK_AUTH_TOKEN"] = New-RandomHex 32 } }

$env["OPENAI_BASE_URL"] = $existing["OPENAI_BASE_URL"]; if (-not $env["OPENAI_BASE_URL"]) { $env["OPENAI_BASE_URL"] = "https://openrouter.ai/api/v1" }
$env["OPENROUTER_API_KEY"] = $existing["OPENROUTER_API_KEY"]; if (-not $env["OPENROUTER_API_KEY"]) { $env["OPENROUTER_API_KEY"] = "" }

$env["REVIEW_MODEL"] = $existing["REVIEW_MODEL"]; if (-not $env["REVIEW_MODEL"]) { $env["REVIEW_MODEL"] = "anthropic/claude-3.5-sonnet" }
$env["REVIEW_MAX_CHARS"] = $existing["REVIEW_MAX_CHARS"]; if (-not $env["REVIEW_MAX_CHARS"]) { $env["REVIEW_MAX_CHARS"] = "18000" }
$env["REVIEW_POST_AS_REVIEW"] = $existing["REVIEW_POST_AS_REVIEW"]; if (-not $env["REVIEW_POST_AS_REVIEW"]) { $env["REVIEW_POST_AS_REVIEW"] = "true" }
$env["REVIEW_LABEL"] = $existing["REVIEW_LABEL"]; if (-not $env["REVIEW_LABEL"]) { $env["REVIEW_LABEL"] = "ai-reviewed" }

$env["GITEA_RUNNER_LABELS"] = $existing["GITEA_RUNNER_LABELS"]; if (-not $env["GITEA_RUNNER_LABELS"]) { $env["GITEA_RUNNER_LABELS"] = "docker:docker://alpine:3.19,linux:host" }

$env["CLOUDFLARED_TUNNEL_TOKEN"] = $existing["CLOUDFLARED_TUNNEL_TOKEN"]; if (-not $env["CLOUDFLARED_TUNNEL_TOKEN"]) { $env["CLOUDFLARED_TUNNEL_TOKEN"] = "" }

# These will be created later
$env["GITEA_TOKEN"] = $existing["GITEA_TOKEN"]; if (-not $env["GITEA_TOKEN"]) { $env["GITEA_TOKEN"] = "" }
$env["GITEA_RUNNER_TOKEN"] = $existing["GITEA_RUNNER_TOKEN"]; if (-not $env["GITEA_RUNNER_TOKEN"]) { $env["GITEA_RUNNER_TOKEN"] = "" }

Write-EnvFile $envPath $env
Log "Wrote $envPath" "OK"

# Render app.ini + runner config
$appTemplate = Join-Path $here "gitea\app.ini.template"
$appOut = Join-Path $here "gitea\app.ini"
$secretKey = $existing["GITEA_SECRET_KEY"]; if (-not $secretKey) { $secretKey = New-RandomHex 32 }
$internalToken = $existing["GITEA_INTERNAL_TOKEN"]; if (-not $internalToken) { $internalToken = New-RandomHex 32 }

$appText = Render-Template $appTemplate @{
  "__GITEA_DOMAIN__" = $env["GITEA_DOMAIN"]
  "__GITEA_ROOT_URL__" = $env["GITEA_ROOT_URL"]
  "__GITEA_SSH_DOMAIN__" = $env["GITEA_SSH_DOMAIN"]
  "__GITEA_SSH_PORT__" = $env["GITEA_SSH_PORT"]
  "__GITEA_DB_PASS__" = $env["GITEA_DB_PASS"]
  "__GITEA_SECRET_KEY__" = $secretKey
  "__GITEA_INTERNAL_TOKEN__" = $internalToken
}
Set-Content -Path $appOut -Value $appText -Encoding UTF8
Log "Rendered gitea/app.ini" "OK"

$runnerTemplate = Join-Path $here "runner\config.yaml.template"
$runnerOut = Join-Path $here "runner\config.yaml"
$runnerText = Render-Template $runnerTemplate @{
  "__NYRA_NETWORK__" = $env["NYRA_NETWORK"]
}
Set-Content -Path $runnerOut -Value $runnerText -Encoding UTF8
Log "Rendered runner/config.yaml" "OK"

# Ensure network
Ensure-DockerNetwork $env["NYRA_NETWORK"]

# Start base services
Log "Starting: gitea-db + gitea" "INFO"
& docker compose -f (Join-Path $here "docker-compose.yml") --env-file $envPath up -d gitea-db gitea

Wait-Http ("http://localhost:$GiteaWebPort/")

# Create admin user (idempotent)
Log "Ensuring admin user '$($env["GITEA_ADMIN_USER"])' exists..." "INFO"
$cfg = "/data/gitea/conf/app.ini"
try {
  $users = Docker-Exec "nyra-gitea" @("gitea","--config",$cfg,"admin","user","list")
  if ($users -match ("^\s*\d+\s+" + [regex]::Escape($env["GITEA_ADMIN_USER"]) + "\s") ) {
    Log "✅ Admin user already exists" "OK"
  } else {
    Log "Creating admin user via gitea CLI..." "INFO"
    $createCmd = @("gitea","--config",$cfg,"admin","user","create",
      "--username",$env["GITEA_ADMIN_USER"],
      "--password",$env["GITEA_ADMIN_PASS"],
      "--email",$env["GITEA_ADMIN_EMAIL"],
      "--admin",
      "--must-change-password=false"
    )
    try { Docker-Exec "nyra-gitea" $createCmd | Out-Null }
    catch {
      # Some builds may not support --must-change-password; retry without.
      $createCmd = @("gitea","--config",$cfg,"admin","user","create",
        "--username",$env["GITEA_ADMIN_USER"],
        "--password",$env["GITEA_ADMIN_PASS"],
        "--email",$env["GITEA_ADMIN_EMAIL"],
        "--admin"
      )
      Docker-Exec "nyra-gitea" $createCmd | Out-Null
    }
    Log "✅ Admin user created" "OK"
  }
} catch {
  Log "WARN: Could not manage admin user via CLI: $($_.Exception.Message)" "WARN"
  Log "You can still finish setup in the web UI at http://localhost:$GiteaWebPort/" "WARN"
}

# Create PAT automatically (Token API requires BasicAuth+password)
# Endpoint: POST /users/:name/tokens (special; requires BasicAuth) per docs.
if (-not $env["GITEA_TOKEN"]) {
  try {
    Log "Creating a Gitea API token for the AI reviewer (via API)..." "INFO"
    $basic = [Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes("$($env["GITEA_ADMIN_USER"]):$($env["GITEA_ADMIN_PASS"])"))
    $headers = @{
      Authorization = "Basic $basic"
      "Content-Type" = "application/json"
      Accept = "application/json"
    }
    $tokenName = "nyra-ai-reviewer"
    $body = @{
      name = $tokenName
      scopes = @("read:repository","write:issue","write:repository")
    } | ConvertTo-Json
    $tokenResp = Invoke-RestMethod -Method Post -Uri ("http://localhost:$GiteaWebPort/api/v1/users/$($env["GITEA_ADMIN_USER"])/tokens") -Headers $headers -Body $body
    if ($tokenResp.sha1) {
      $env["GITEA_TOKEN"] = $tokenResp.sha1
      Write-EnvFile $envPath $env
      Log "✅ Created GITEA_TOKEN and saved to .env.gitea" "OK"
    } else {
      Log "WARN: Token API response didn't include token. You may need to create a PAT in UI." "WARN"
    }
  } catch {
    Log "WARN: Could not create PAT via API: $($_.Exception.Message)" "WARN"
    Log "Create one manually: User Settings → Applications → Manage Access Tokens" "WARN"
  }
}

# Generate runner registration token via gitea CLI (optional)
if ($EnableActions -and -not $env["GITEA_RUNNER_TOKEN"]) {
  try {
    Log "Generating runner registration token via gitea CLI..." "INFO"
    $tok = Docker-Exec "nyra-gitea" @("gitea","--config",$cfg,"actions","generate-runner-token") | Select-Object -First 1
    $tok = $tok.Trim()
    if ($tok) {
      $env["GITEA_RUNNER_TOKEN"] = $tok
      Write-EnvFile $envPath $env
      Log "✅ Saved GITEA_RUNNER_TOKEN to .env.gitea" "OK"
    }
  } catch {
    Log "WARN: Could not generate runner token automatically: $($_.Exception.Message)" "WARN"
    Log "You can also get it from: /-/admin/actions/runners (instance level) when Actions are enabled." "WARN"
  }
}

# Bring up optional profiles
if ($EnableAIReviewer) {
  if (-not $env["OPENROUTER_API_KEY"]) {
    throw "OPENROUTER_API_KEY is empty in .env.gitea. Add it, then rerun with -EnableAIReviewer."
  }
  Log "Starting AI reviewer (profile: ai)" "INFO"
  & docker compose -f (Join-Path $here "docker-compose.yml") --env-file $envPath --profile ai up -d
  Log "✅ AI reviewer started. Next: run scripts/Create-Webhook.ps1 for each repo you want reviewed." "OK"
}

if ($EnableActions) {
  if (-not $env["GITEA_RUNNER_TOKEN"]) {
    throw "GITEA_RUNNER_TOKEN is empty. Re-run with -EnableActions after token is generated, or set it manually."
  }
  Log "Starting actions runner (profile: actions)" "INFO"
  & docker compose -f (Join-Path $here "docker-compose.yml") --env-file $envPath --profile actions up -d
  Log "✅ Actions runner started." "OK"
}

if ($EnablePublicTunnel) {
  if (-not $env["CLOUDFLARED_TUNNEL_TOKEN"]) {
    throw "CLOUDFLARED_TUNNEL_TOKEN is empty. Add it to .env.gitea, then rerun with -EnablePublicTunnel."
  }
  Log "Starting cloudflared tunnel (profile: public)" "INFO"
  & docker compose -f (Join-Path $here "docker-compose.yml") --env-file $envPath --profile public up -d
  Log "✅ Cloudflared started." "OK"
}

# Summary
$summary = @()
$summary += "# NYRA Gitea Bootstrap Summary"
$summary += ""
$summary += "- Machine: $MachineRole"
$summary += "- Web: http://localhost:$GiteaWebPort/"
$summary += "- SSH: ssh://git@localhost:$GiteaSshPort/"
$summary += "- ROOT_URL (links): $($env["GITEA_ROOT_URL"])"
$summary += ""
$summary += "## Admin creds (stored in .env.gitea)"
$summary += "- user: $($env["GITEA_ADMIN_USER"])"
$summary += "- pass: $($env["GITEA_ADMIN_PASS"])"
$summary += ""
$summary += "## Next moves"
$summary += "1) Log in and create a repo."
$summary += "2) (Optional) Enable Actions per-repo: Repo → Settings → Actions."
$summary += "3) (Optional AI) Create webhook:"
$summary += "   `.\scripts\Create-Webhook.ps1 -Owner <owner> -Repo <repo>`"
$summaryPath = Join-Path $here "gitea-setup-summary-$MachineRole.md"
Set-Content -Path $summaryPath -Value ($summary -join "`n") -Encoding UTF8
Log "Wrote $summaryPath" "OK"

Log "Done. Like a tidy lodge: square, level, and plumb. 🐾" "OK"
