services:
  postgres:
    ports:
      - '0.0.0.0:${POSTGRES_PORT:-5432}:5432'
  redis:
    ports:
      - '0.0.0.0:${REDIS_PORT:-6379}:6379'
  mongo:
    ports:
      - '0.0.0.0:${MONGO_PORT:-27017}:27017'
  infisical:
    ports:
      - '0.0.0.0:${INFISICAL_PORT:-8086}:8080'
  n8n:
    ports:
      - '0.0.0.0:${N8N_PORT:-5678}:5678'
  activepieces:
    ports:
      - '0.0.0.0:${ACTIVEPIECES_PORT:-8082}:80'
  prometheus:
    ports:
      - '0.0.0.0:${PROMETHEUS_PORT:-9090}:9090'
  loki:
    ports:
      - '0.0.0.0:${LOKI_PORT:-3100}:3100'
  grafana:
    ports:
      - '0.0.0.0:${GRAFANA_PORT:-3003}:3000'
  cadvisor:
    ports:
      - '0.0.0.0:${CADVISOR_PORT:-8081}:8080'
  cloudflared:
    restart: unless-stopped
