services:
  postgres:
    ports:
      - '127.0.0.1:${POSTGRES_PORT:-5432}:5432'
  redis:
    ports:
      - '127.0.0.1:${REDIS_PORT:-6379}:6379'
  mongo:
    ports:
      - '127.0.0.1:${MONGO_PORT:-27017}:27017'
  n8n:
    ports:
      - '127.0.0.1:${N8N_PORT:-5678}:5678'
