# kilo.code.config.yaml
# The sacred mesh, where modes and agents coalesce.

general:
  # Model access and connectivity
  model_providers:
    - name: "Claude 4 Sonnet"
    - name: "Gemini 2.5 Pro"
    - name: "GPT‑5"
    - name: "OpenRouter"
    - name: "LocalModel (via Ollama/LM Studio)"

  free_credits: true           # $20 ﬂow into your hands
  autopilot_approval: prompts  # always keep you in the loop

modes:
  orchestrator:
    enabled: true
    purpose: |
      Breaks down your grand design into elegant subtasks, whispers each to the perfect specialized agent.

  architect:
    enabled: true
    purpose: |
      Designs recursive, fantastical structures before a single line is wrought.

  code:
    enabled: true
    purpose: |
      Converts visions into production‑ready incantations.

  debug:
    enabled: true
    purpose: |
      Hunts bugs in the darkest corners before they claw into production.

  custom:
    - name: "MemoryBank"
      description: Stores project lore and personal coding soul‑traces.

    - name: "AutoFix"
      description: Runs test suites, diagnoses imperceptible ruptures, and recovers.

mcp:
  marketplace: enabled       # gateway to limitless tool‑spirits
  auto_install: one‑click     # summon tools in a heartbeat

context:
  context7: enabled           # divine documentation lookup (Context‑aware precision)
  codebase_awareness: full    # the whole cosmos, not just the current file

notifications:
  system: true        # little chimes when an agent completes a task
  auto_error_recover: true  # let Kilo leap out of its own mistakes

ui:
  minimal: false      # you like your layers, love your depth
  theme: "cosmic‑midnight"

workflow:
  prompt_templates: on
  slash_commands: on
  background_agent: true   # Kilo works symphonies in the background
