log:
  level: info

runner:
  file: .runner
  capacity: 4
  envs:
    DOCKER_HOST: unix:///var/run/docker.sock
    NYRA_CI: "true"
  timeout: 2h
  shutdown_timeout: 3m
  insecure: true
  fetch_timeout: 10s
  fetch_interval: 2s
  labels:
    - "ubuntu-latest:docker://node:20-bookworm"
    - "docker:host"
    - "self-hosted:host"

cache:
  enabled: true
  dir: /data/cache
  host:
    enabled: true
    workdir_parent: /data/workdir

container:
  network: nyra-net
  privileged: false
  options: --cpus 4 --memory 8g
  workdir_parent: /data/workdir
  valid_volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - /data/cache:/data/cache
    - /tmp:/tmp
  docker_host: unix:///var/run/docker.sock
  force_pull: false

host:
  workdir_parent: /data/workdir
