/**
 * Cloudflare Tunnel Service
 * Handles Cloudflare Tunnel API integration and configuration
 */

import { CloudflareTunnelConfig, CloudflareTunnelService, TunnelConnectionTest } from '../types/manifest';

export interface CloudflareApiResponse {
  success: boolean;
  errors: Array<{ code: number; message: string }>;
  messages: string[];
  result?: any;
}

export interface TunnelCreateResponse {
  id: string;
  name: string;
  created_at: string;
  connections: any[];
}

export class CloudflareTunnelService {
  private apiToken: string;
  private baseUrl = 'https://api.cloudflare.com/client/v4';

  constructor(apiToken: string) {
    this.apiToken = apiToken;
  }

  /**
   * Get account ID from API token
   */
  async getAccountId(): Promise<string> {
    try {
      const response = await fetch(`${this.baseUrl}/accounts`, {
        headers: {
          Authorization: `Bearer ${this.apiToken}`,
          'Content-Type': 'application/json',
        },
      });

      const data: CloudflareApiResponse = await response.json();

      if (!data.success || !data.result || data.result.length === 0) {
        throw new Error('Failed to fetch account ID');
      }

      return data.result[0].id;
    } catch (error) {
      throw new Error(`Failed to get account ID: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Create a new Cloudflare Tunnel
   */
  async createTunnel(accountId: string, tunnelName: string): Promise<TunnelCreateResponse> {
    try {
      const response = await fetch(
        `${this.baseUrl}/accounts/${accountId}/tunnels`,
        {
          method: 'POST',
          headers: {
            Authorization: `Bearer ${this.apiToken}`,
            'Content-Type': 'application/json',
          },
          body: JSON.stringify({
            name: tunnelName,
            tunnel_secret: this.generateTunnelSecret(),
          }),
        }
      );

      const data: CloudflareApiResponse = await response.json();

      if (!data.success) {
        throw new Error(
          data.errors?.[0]?.message || 'Failed to create tunnel'
        );
      }

      return data.result;
    } catch (error) {
      throw new Error(`Failed to create tunnel: ${error instanceof Error ? error.message : 'Unknown error'}`);
    }
  }

  /**
   * Generate tunnel configuration file content
   */
  generateTunnelConfig(
    tunnelId: string,
    services: CloudflareTunnelService[]
  ): string {
    const ingress = services
      .filter((s) => s.enabled)
      .map((service) => ({
        hostname: service.hostname || `${service.name}.tunnel.cloudflare.com`,
        service: `${service.protocol}://localhost:${service.port}`,
      }));

    // Add catch-all rule
    ingress.push({ service: 'http_status:404' });

    const config = {
      tunnel: tunnelId,
      'credentials-file': `/root/.cloudflared/${tunnelId}.json`,
      ingress,
    };

    return `# Cloudflare Tunnel Configuration
# Generated by Project Nyra Bootstrap Installer

${Object.entries(config)
  .map(([key, value]) => {
    if (key === 'ingress') {
      return `ingress:\n${(value as any[])
        .map((item: any) => {
          if (item.hostname) {
            return `  - hostname: ${item.hostname}\n    service: ${item.service}`;
          }
          return `  - service: ${item.service}`;
        })
        .join('\n')}`;
    }
    return `${key}: ${value}`;
  })
  .join('\n')}
`;
  }

  /**
   * Generate cloudflared installation script
   */
  generateInstallScript(tunnelId: string, tunnelToken: string): string {
    return `#!/bin/bash
# Cloudflare Tunnel Installation Script
# Generated by Project Nyra Bootstrap Installer

set -e

echo "Installing cloudflared..."

# Detect OS and install cloudflared
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Debian/Ubuntu
    if command -v apt-get &> /dev/null; then
        curl -L --output cloudflared.deb https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared.deb
        rm cloudflared.deb
    # RedHat/CentOS
    elif command -v yum &> /dev/null; then
        sudo yum install -y https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-x86_64.rpm
    fi
elif [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS
    brew install cloudflare/cloudflare/cloudflared
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "win32" ]]; then
    # Windows (via Scoop or manual download)
    echo "Please download cloudflared from https://github.com/cloudflare/cloudflared/releases"
    exit 1
fi

echo "Installing tunnel service..."

# Create credentials directory
sudo mkdir -p /root/.cloudflared

# Install tunnel
sudo cloudflared tunnel install ${tunnelToken}

# Create systemd service
sudo cloudflared service install

# Start the service
sudo systemctl start cloudflared
sudo systemctl enable cloudflared

echo "Cloudflare Tunnel installed and started successfully!"
echo "Tunnel ID: ${tunnelId}"
`;
  }

  /**
   * Generate PowerShell installation script for Windows
   */
  generateWindowsInstallScript(tunnelId: string, tunnelToken: string): string {
    return `# Cloudflare Tunnel Installation Script for Windows
# Generated by Project Nyra Bootstrap Installer

Write-Host "Installing cloudflared for Windows..." -ForegroundColor Green

# Download cloudflared
$downloadUrl = "https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-windows-amd64.exe"
$installPath = "$env:ProgramFiles\\cloudflared"
$exePath = "$installPath\\cloudflared.exe"

# Create directory
New-Item -ItemType Directory -Force -Path $installPath | Out-Null

# Download
Write-Host "Downloading cloudflared..."
Invoke-WebRequest -Uri $downloadUrl -OutFile $exePath

# Add to PATH
$currentPath = [Environment]::GetEnvironmentVariable("Path", "Machine")
if ($currentPath -notlike "*$installPath*") {
    [Environment]::SetEnvironmentVariable(
        "Path",
        "$currentPath;$installPath",
        "Machine"
    )
}

# Install tunnel service
Write-Host "Installing tunnel service..."
& $exePath tunnel install ${tunnelToken}

# Create Windows service
& $exePath service install

# Start the service
Start-Service cloudflared

Write-Host "Cloudflare Tunnel installed and started successfully!" -ForegroundColor Green
Write-Host "Tunnel ID: ${tunnelId}"
`;
  }

  /**
   * Test tunnel connectivity
   */
  async testConnection(url: string): Promise<TunnelConnectionTest> {
    const startTime = Date.now();

    try {
      const response = await fetch(url, {
        method: 'HEAD',
        signal: AbortSignal.timeout(10000), // 10 second timeout
      });

      const responseTime = Date.now() - startTime;

      return {
        service: '',
        url,
        status: response.ok ? 'success' : 'failed',
        responseTime,
        error: response.ok ? undefined : `HTTP ${response.status}`,
      };
    } catch (error) {
      return {
        service: '',
        url,
        status: 'failed',
        error: error instanceof Error ? error.message : 'Connection failed',
      };
    }
  }

  /**
   * Generate a random tunnel secret
   */
  private generateTunnelSecret(): string {
    const array = new Uint8Array(32);
    crypto.getRandomValues(array);
    return Array.from(array, (byte) => byte.toString(16).padStart(2, '0')).join(
      ''
    );
  }

  /**
   * Validate API token has required permissions
   */
  async validateToken(): Promise<{ valid: boolean; message: string }> {
    try {
      const response = await fetch(`${this.baseUrl}/user/tokens/verify`, {
        headers: {
          Authorization: `Bearer ${this.apiToken}`,
          'Content-Type': 'application/json',
        },
      });

      const data: CloudflareApiResponse = await response.json();

      if (!data.success) {
        return {
          valid: false,
          message: 'Invalid API token',
        };
      }

      return {
        valid: true,
        message: 'Token validated successfully',
      };
    } catch (error) {
      return {
        valid: false,
        message: error instanceof Error ? error.message : 'Token validation failed',
      };
    }
  }
}

/**
 * Helper function to detect current PC type
 */
export function detectPCType(): string {
  // Check environment variables or system info
  const hostname = typeof window !== 'undefined' ? window.location.hostname : '';

  if (hostname.includes('orchestrator') || hostname.includes('mini')) {
    return 'orchestrator-mini';
  }

  if (hostname.includes('rtx3090')) {
    return 'worker-rtx3090ti';
  }

  if (hostname.includes('rtx3060')) {
    return 'worker-rtx3060';
  }

  if (hostname.includes('rtx5090')) {
    return 'worker-rtx5090';
  }

  // Default fallback
  return 'unknown';
}
