_format_version: "1.1"
services:
  - name: rest
    url: http://supabase-rest:3000
    routes:
      - name: rest
        paths:
          - /rest/v1
  - name: auth
    url: http://supabase-auth:8081
    routes:
      - name: auth
        paths:
          - /auth/v1
