#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PROJECT_ID="${INFISICAL_PROJECT_ID:-8374cea9-e5e8-4050-bda4-b91f25ab30ef}"
INFISICAL_ENV_NAME="${INFISICAL_ENV:-dev}"
INFISICAL_ENV_NAMES="${INFISICAL_ENVS:-${INFISICAL_ENV:-dev}}"
INFISICAL_SOURCE_ENV="${INFISICAL_SOURCE_ENV:-prod}"
GENERATED_ENV="secrets/infisical/agent-infra.generated.env"

usage() {
  cat <<'USAGE'
Usage: scripts/infisical/agent-infra-secrets.sh <generate|audit|push|export-template>

generate        Create/reuse local generated secrets in secrets/infisical/agent-infra.generated.env.
audit           Check which required secrets exist in Infisical and local environment without printing values.
push            Push generated/retrieved values to Infisical.
export-template Print a key/path manifest as CSV.

Environment selection:
  INFISICAL_ENV=prod                 single environment
  INFISICAL_ENVS=dev,stag,prod       multiple environments
  INFISICAL_SOURCE_ENV=prod          fallback source env for existing secret values
USAGE
}

rand_hex() {
  openssl rand -hex "${1:-32}"
}

rand_b64url() {
  openssl rand -base64 "${1:-48}" | tr '+/' '-_' | tr -d '=\n'
}

ensure_generated_file() {
  mkdir -p "$(dirname "$GENERATED_ENV")"
  chmod 700 "$(dirname "$GENERATED_ENV")"

  if [[ ! -f "$GENERATED_ENV" ]]; then
    umask 077
    cat >"$GENERATED_ENV" <<EOF
# Generated by scripts/infisical/agent-infra-secrets.sh.
# Do not commit.
PAPERCLIP_DB_PASSWORD=$(rand_b64url 36)
PAPERCLIP_SESSION_SECRET=$(rand_b64url 48)
SEARXNG_SECRET=$(rand_b64url 48)
BROWSERLESS_TOKEN=$(rand_b64url 36)
LETTA_DB_PASSWORD=$(rand_b64url 36)
LETTA_SERVER_PASSWORD=$(rand_b64url 48)
QDRANT_API_KEY=$(rand_b64url 36)
EOF
  fi

  chmod 600 "$GENERATED_ENV"
}

load_local_sources() {
  ensure_generated_file
  set -a
  # shellcheck disable=SC1090
  source "$GENERATED_ENV"
  for file in \
    infra/env/composio.env.example \
    infra/environments/voice-mesh.example.env \
    infra/environments/memory.example.env \
    infra/environments/oracle-agent-utils.example.env
  do
    [[ -f "$file" ]] || continue
    # Load only defaults for variables not already present.
    while IFS='=' read -r key value; do
      [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
      [[ -n "${!key:-}" ]] && continue
      value="${value%%#*}"
      value="${value%$'\r'}"
      export "$key=$value"
    done < <(rg -N '^[A-Za-z_][A-Za-z0-9_]*=' "$file" || true)
  done
  set +a

  export COMPOSIO_DEFAULT_USER_ID="${COMPOSIO_DEFAULT_USER_ID:-nyra-system}"
  export COMPOSIO_MCP_TRANSPORT="${COMPOSIO_MCP_TRANSPORT:-streamable-http}"
  export COMPOSIO_MCP_SERVER_NAME="${COMPOSIO_MCP_SERVER_NAME:-composio}"
  export COMPOSIO_TOOLKITS_ALLOW="${COMPOSIO_TOOLKITS_ALLOW:-jira,slack,twenty}"
  export COMPOSIO_EXECUTION_POLICY="${COMPOSIO_EXECUTION_POLICY:-require-user-bound-connection}"
  export RTX3060_LAN_IP="${RTX3060_LAN_IP:-192.168.1.36}"
  export RTX3090TI_LAN_IP="${RTX3090TI_LAN_IP:-192.168.1.39}"
  export RTX5090_LAN_IP="${RTX5090_LAN_IP:-192.168.1.50}"
  export VOICE_PTP_INTERFACE="${VOICE_PTP_INTERFACE:-eno1}"
  export ASSISTANT_GATEWAY_URL="${ASSISTANT_GATEWAY_URL:-http://orchestrator.lan:3400}"
  export LITELLM_BASE_URL="${LITELLM_BASE_URL:-http://orchestrator.lan:4000/v1}"
  export MEMORY_BASE_URL="${MEMORY_BASE_URL:-http://oracle-vps.lan:5000}"

  if [[ -z "${LITELLM_API_KEY:-}" && -n "${LITELLM_MASTER_KEY:-}" ]]; then
    export LITELLM_API_KEY="$LITELLM_MASTER_KEY"
  fi
}

manifest_csv() {
  cat <<'CSV'
path,key,source,required
/clients/paperclip,PAPERCLIP_DB_PASSWORD,generated,yes
/clients/paperclip,PAPERCLIP_SESSION_SECRET,generated,yes
/clients/searxng,SEARXNG_SECRET,generated,yes
/clients/browserless,BROWSERLESS_TOKEN,generated,yes
/clients/letta,LETTA_DB_PASSWORD,generated,yes
/clients/letta,LETTA_SERVER_PASSWORD,generated,yes
/databases/qdrant-local,QDRANT_API_KEY,generated,yes
/providers/openai,OPENAI_API_KEY,environment,yes
/providers/anthropic,ANTHROPIC_API_KEY,environment,no
/providers/litellm,LITELLM_MASTER_KEY,environment,yes
/clients/composio,COMPOSIO_API_KEY,manual,yes
/clients/composio,COMPOSIO_MCP_SERVER_ID,manual,yes
/clients/composio,COMPOSIO_MCP_URL,manual,yes
/clients/composio,COMPOSIO_DEFAULT_USER_ID,config,yes
/clients/composio,COMPOSIO_MCP_TRANSPORT,config,yes
/clients/composio,COMPOSIO_MCP_SERVER_NAME,config,yes
/clients/composio,COMPOSIO_TOOLKITS_ALLOW,config,yes
/clients/composio,COMPOSIO_EXECUTION_POLICY,config,yes
CSV
}

value_for_key() {
  local key="$1"
  printf '%s' "${!key:-}"
}

split_envs() {
  tr ',' '\n' <<<"$INFISICAL_ENV_NAMES" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//' | awk 'NF'
}

is_placeholder() {
  local value="$1"
  [[ -z "$value" || "$value" == replace-me || "$value" == replace-* || "$value" == *'${'* || "$value" == change-me* ]]
}

infisical_get_status() {
  local env_name="$1"
  local path="$2"
  local key="$3"
  local value
  value="$(infisical secrets get "$key" \
    --projectId "$PROJECT_ID" \
    --env "$env_name" \
    --path "$path" \
    --plain \
    --silent 2>/dev/null || true)"
  if [[ -n "$value" ]]; then
    printf 'present'
  else
    printf 'missing'
  fi
}

infisical_secret_value() {
  local env_name="$1"
  local path="$2"
  local key="$3"
  local value
  value="$(infisical secrets get "$key" \
    --projectId "$PROJECT_ID" \
    --env "$env_name" \
    --path "$path" \
    --plain \
    --silent 2>/dev/null || true)"
  printf '%s' "$value"
}

ensure_folder() {
  local env_name="$1"
  local full="$2"
  local parent="/"
  local current=""
  local part
  IFS=/ read -ra parts <<<"${full#/}"
  for part in "${parts[@]}"; do
    [[ -n "$part" ]] || continue
    if [[ "$parent" == "/" ]]; then
      current="/$part"
    else
      current="$parent/$part"
    fi
    if ! infisical secrets folders get \
      --projectId "$PROJECT_ID" \
      --env "$env_name" \
      --path "$parent" \
      --output json \
      --silent 2>/dev/null | jq -e --arg name "$part" '.[]? | select(.folderName == $name)' >/dev/null; then
      infisical secrets folders create \
        --projectId "$PROJECT_ID" \
        --env "$env_name" \
        --path "$parent" \
        --name "$part" \
        --silent >/dev/null
      printf 'created folder %-24s %s\n' "$env_name" "$current"
    fi
    parent="$current"
  done
}

value_for_manifest_entry() {
  local env_name="$1"
  local path="$2"
  local key="$3"
  local source="$4"
  local value

  value="$(value_for_key "$key")"
  if ! is_placeholder "$value"; then
    printf '%s' "$value"
    return 0
  fi

  value="$(infisical_secret_value "$env_name" "$path" "$key")"
  if [[ -n "$value" ]]; then
    printf '%s' "$value"
    return 0
  fi

  if [[ "$env_name" != "$INFISICAL_SOURCE_ENV" ]]; then
    value="$(infisical_secret_value "$INFISICAL_SOURCE_ENV" "$path" "$key")"
    if [[ -n "$value" ]]; then
      printf '%s' "$value"
      return 0
    fi
  fi

  printf ''
}

set_secret() {
  local env_name="$1"
  local path="$2"
  local key="$3"
  local value="$4"
  infisical secrets set "$key=$value" \
    --projectId "$PROJECT_ID" \
    --env "$env_name" \
    --path "$path" \
    --silent >/dev/null
}

audit() {
  load_local_sources
  printf 'Infisical project: %s\n' "$PROJECT_ID"
  printf 'Infisical envs: %s\n' "$INFISICAL_ENV_NAMES"
  split_envs | while read -r env_name; do
    printf '\n[%s]\n' "$env_name"
    printf '%-28s %-34s %-12s %-12s\n' "PATH" "KEY" "LOCAL/SOURCE" "INFISICAL"
    manifest_csv | tail -n +2 | while IFS=',' read -r path key source required; do
      value="$(value_for_manifest_entry "$env_name" "$path" "$key" "$source")"
      if is_placeholder "$value"; then
        local_status="missing"
      else
        local_status="available"
      fi
      remote_status="$(infisical_get_status "$env_name" "$path" "$key")"
      printf '%-28s %-34s %-12s %-12s\n' "$path" "$key" "$local_status" "$remote_status"
    done
  done
}

push() {
  load_local_sources
  local pushed=0
  local skipped=0

  split_envs | while read -r env_name; do
    printf '[%s]\n' "$env_name"
    manifest_csv | tail -n +2 | while IFS=',' read -r path key source required; do
      ensure_folder "$env_name" "$path"
      value="$(value_for_manifest_entry "$env_name" "$path" "$key" "$source")"
      if is_placeholder "$value"; then
        printf 'skip %-34s missing value for %s\n' "$key" "$env_name"
        skipped=$((skipped + 1))
        continue
      fi
      set_secret "$env_name" "$path" "$key" "$value"
      printf 'set  %-34s %s %s\n' "$key" "$env_name" "$path"
      pushed=$((pushed + 1))
    done
  done
}

cmd="${1:-}"
case "$cmd" in
  generate)
    ensure_generated_file
    printf 'generated/reused %s\n' "$GENERATED_ENV"
    ;;
  audit)
    audit
    ;;
  push)
    push
    ;;
  export-template)
    manifest_csv
    ;;
  *)
    usage
    exit 2
    ;;
esac
