#!/usr/bin/env python3
"""Audit Infisical usage across Project Nyra infrastructure files."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
REPORT_PATH = ROOT / "docs" / "reports" / "INFISICAL_CAPABILITY_AUDIT.md"
SCAN_GLOBS = (
    "infra/hosts/**/*.yml",
    "infra/hosts/**/*.yaml",
    "infra/hosts/**/*.md",
    "docs/**/*.md",
    "services/**/.env.example",
    "apps/**/.env.example",
)

CAPABILITIES = {
    "Secrets Sync / Agent": ("infisical", "INFISICAL_", "infisical-agent"),
    "Agent Vault": ("agent-vault", "vault"),
    "KMS": ("kms", "encryption"),
    "PAM": ("pam", "ssh ca", "database access"),
    "Secret Scanning": ("secret scanning", "trufflehog", "gitleaks"),
}

INLINE_SECRET = re.compile(
    r"(password|token|secret|api[_-]?key)\s*[:=]\s*['\"]?(?!\$\{)[A-Za-z0-9_.:/@+-]{8,}",
    re.I,
)


def iter_files() -> list[Path]:
    files: set[Path] = set()
    for pattern in SCAN_GLOBS:
        files.update(path for path in ROOT.glob(pattern) if path.is_file())
    return sorted(files)


def scan() -> dict[str, object]:
    capability_hits = {name: [] for name in CAPABILITIES}
    inline_flags = []

    for path in iter_files():
        text = path.read_text(encoding="utf-8", errors="ignore")
        lower = text.lower()
        rel = str(path.relative_to(ROOT))

        for capability, signals in CAPABILITIES.items():
            if any(signal.lower() in lower for signal in signals):
                capability_hits[capability].append(rel)

        for lineno, line in enumerate(text.splitlines(), start=1):
            if INLINE_SECRET.search(line):
                inline_flags.append((rel, lineno, line.strip()[:140]))

    return {"capability_hits": capability_hits, "inline_flags": inline_flags}


def render(result: dict[str, object]) -> str:
    capability_hits = result["capability_hits"]
    inline_flags = result["inline_flags"]

    lines = [
        "# Infisical Capability Audit",
        "",
        "Generated by `scripts/infra/audit-infisical-usage.py`.",
        "",
        "## Capability Coverage",
        "",
        "| Capability | Evidence files | Status |",
        "| --- | ---: | --- |",
    ]

    for capability, files in capability_hits.items():
        status = "present" if files else "missing repository evidence"
        lines.append(f"| {capability} | {len(files)} | {status} |")

    lines.extend(["", "## Key Evidence", ""])
    for capability, files in capability_hits.items():
        lines.append(f"### {capability}")
        for rel in files[:12]:
            lines.append(f"- `{rel}`")
        if not files:
            lines.append("- No repository references found.")
        lines.append("")

    lines.extend(
        [
            "## Inline Secret-Looking Values",
            "",
            "Review these for migration to Infisical, `.env` placeholders, or documented local-only defaults. Values are truncated and should not be treated as complete secrets.",
            "",
            "| File | Line | Snippet |",
            "| --- | ---: | --- |",
        ]
    )
    for rel, lineno, snippet in inline_flags[:100]:
        safe = snippet.replace("|", "\\|")
        lines.append(f"| `{rel}` | {lineno} | `{safe}` |")
    if not inline_flags:
        lines.append("| none | 0 | none |")

    lines.extend(
        [
            "",
            "## Recommendations",
            "",
            "- Use Infisical Agent or template volume mounts for runtime `.env` generation instead of committing service secrets.",
            "- Use KMS-backed envelope encryption for loan documents, transcript artifacts, and memory snapshots that may contain PII.",
            "- Use PAM for temporary database, SSH, Redis, and Kubernetes access instead of standing operator credentials.",
            "- Keep secret scanning in pre-commit and CI, with suppressions documented in the security runbook.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write markdown report")
    args = parser.parse_args()

    report = render(scan())
    if args.write:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(report, encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
