#!/usr/bin/env python3
"""Audit Project Nyra host compose files for Nexus Router integration."""

from __future__ import annotations

import argparse
import re
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - fallback is handled at runtime.
    yaml = None


ROOT = Path(__file__).resolve().parents[2]
HOSTS_DIR = ROOT / "infra" / "hosts"
REPORT_PATH = ROOT / "docs" / "reports" / "NEXUS_STACK_INTEGRATION_AUDIT.md"

NEXUS_SIGNALS = (
    "NEXUS_ROUTER_URL",
    "NEXUS_BASE_URL",
    "NEXUS_URL",
    "GRAFBASE_NEXUS",
    "nexus-router",
    "nyra-nexus",
)
SHOULD_ROUTE_SIGNALS = (
    "agent",
    "assistant",
    "claw",
    "letta",
    "litellm",
    "mcp",
    "mem0",
    "memory",
    "memos",
    "openclaw",
    "openmemory",
    "orchestrator",
    "worker",
)
PRIVATE_DATA_PLANE_SIGNALS = (
    "browserless",
    "clickhouse",
    "db",
    "falkordb",
    "grafana",
    "loki",
    "postgres",
    "prometheus",
    "promtail",
    "qdrant",
    "redis",
    "searxng",
)
LOWER_SECRET_PATTERN = re.compile(r"(password|token|secret|key)\s*[:=]\s*[^$\s{}]+", re.I)


def load_compose(path: Path) -> dict[str, Any]:
    if yaml is None:
        return {"services": text_scan_services(path)}
    with path.open("r", encoding="utf-8", errors="ignore") as handle:
        data = yaml.safe_load(handle) or {}
    return data if isinstance(data, dict) else {}


def text_scan_services(path: Path) -> dict[str, dict[str, Any]]:
    services: dict[str, dict[str, Any]] = {}
    in_services = False
    for line in path.read_text(encoding="utf-8", errors="ignore").splitlines():
        if line.startswith("services:"):
            in_services = True
            continue
        if in_services and line and not line.startswith((" ", "\t")):
            break
        match = re.match(r"^\s{2}([A-Za-z0-9_.-]+):\s*$", line)
        if in_services and match:
            services[match.group(1)] = {"_text": ""}
    return services


def service_blob(name: str, service: Any) -> str:
    return f"{name}\n{service}".lower()


def has_any(blob: str, signals: tuple[str, ...]) -> bool:
    return any(signal.lower() in blob for signal in signals)


def host_from_path(path: Path) -> str:
    rel = path.relative_to(HOSTS_DIR)
    return rel.parts[0]


def scan() -> dict[str, Any]:
    rows: list[dict[str, Any]] = []
    host_stats: dict[str, dict[str, int]] = defaultdict(
        lambda: {"services": 0, "integrated": 0, "gaps": 0, "compose_files": 0}
    )
    nexus_config = (HOSTS_DIR / "oracle-vps" / "nexus.toml").read_text(
        encoding="utf-8", errors="ignore"
    ).lower()

    for path in sorted(HOSTS_DIR.rglob("docker-compose*.yml")):
        if "deprecated" in path.parts:
            continue
        host = host_from_path(path)
        host_stats[host]["compose_files"] += 1
        compose = load_compose(path)
        services = compose.get("services") or {}
        if not isinstance(services, dict):
            continue

        for name, service in services.items():
            blob = service_blob(name, service)
            should_route = has_any(blob, SHOULD_ROUTE_SIGNALS)
            integrated = has_any(blob, NEXUS_SIGNALS) or name.lower() in nexus_config
            hardcoded_secret = bool(LOWER_SECRET_PATTERN.search(str(service)))

            host_stats[host]["services"] += 1
            if integrated:
                host_stats[host]["integrated"] += 1
            private_data_plane = has_any(blob, PRIVATE_DATA_PLANE_SIGNALS)
            if should_route and not integrated and not private_data_plane:
                host_stats[host]["gaps"] += 1

            rows.append(
                {
                    "host": host,
                    "compose": str(path.relative_to(ROOT)),
                    "service": name,
                    "should_route": should_route,
                    "private_data_plane": private_data_plane,
                    "integrated": integrated,
                    "hardcoded_secret": hardcoded_secret,
                }
            )

    return {"rows": rows, "host_stats": dict(host_stats)}


def render(result: dict[str, Any]) -> str:
    rows = result["rows"]
    host_stats = result["host_stats"]
    gaps = [
        row
        for row in rows
        if row["should_route"] and not row["integrated"] and not row["private_data_plane"]
    ]
    private = [row for row in rows if row["should_route"] and row["private_data_plane"]]
    hardcoded = [row for row in rows if row["hardcoded_secret"]]

    lines = [
        "# Nexus Stack Integration Audit",
        "",
        "Generated by `scripts/infra/audit-nexus-integration.py`.",
        "",
        "## Summary",
        "",
        "| Host | Compose files | Services | Nexus signals | Candidate gaps |",
        "| --- | ---: | ---: | ---: | ---: |",
    ]

    for host in sorted(host_stats):
        stats = host_stats[host]
        lines.append(
            f"| {host} | {stats['compose_files']} | {stats['services']} | "
            f"{stats['integrated']} | {stats['gaps']} |"
        )

    lines.extend(
        [
            "",
            "## Candidate Nexus Gaps",
            "",
            "These services contain agent, MCP, memory, model, or worker signals but no explicit Nexus Router URL/config signal.",
            "",
            "| Host | Service | Compose |",
            "| --- | --- | --- |",
        ]
    )
    for row in gaps[:80]:
        lines.append(f"| {row['host']} | {row['service']} | `{row['compose']}` |")
    if not gaps:
        lines.append("| none | none | none |")

    lines.extend(
        [
            "",
            "## Private Data-Plane Services",
            "",
            "These services matched memory/model keywords but should normally stay private rather than route through Nexus directly.",
            "",
            "| Host | Service | Compose |",
            "| --- | --- | --- |",
        ]
    )
    for row in private[:80]:
        lines.append(f"| {row['host']} | {row['service']} | `{row['compose']}` |")
    if not private:
        lines.append("| none | none | none |")

    lines.extend(
        [
            "",
            "## Secret Hygiene Flags",
            "",
            "Rows below matched simple inline secret-looking values and should be reviewed for Infisical/env-file migration.",
            "",
            "| Host | Service | Compose |",
            "| --- | --- | --- |",
        ]
    )
    for row in hardcoded[:80]:
        lines.append(f"| {row['host']} | {row['service']} | `{row['compose']}` |")
    if not hardcoded:
        lines.append("| none | none | none |")

    lines.extend(
        [
            "",
            "## Recommendations",
            "",
            "- Keep `infra/hosts/oracle-vps/nexus.toml` as the canonical Nexus Router config.",
            "- Route agent and MCP-facing services through Nexus unless they are explicitly marked as private data-plane services.",
            "- Keep OpenMemory, mem0, and memOS behind private host binds or Tailscale/Cloudflare Access.",
            "- Refresh this report after each compose-stack consolidation.",
        ]
    )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--write", action="store_true", help="write markdown report")
    args = parser.parse_args()

    report = render(scan())
    if args.write:
        REPORT_PATH.parent.mkdir(parents=True, exist_ok=True)
        REPORT_PATH.write_text(report, encoding="utf-8")
    else:
        print(report)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
