#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

PROJECT_ID="${INFISICAL_PROJECT_ID:-8374cea9-e5e8-4050-bda4-b91f25ab30ef}"
INFISICAL_ENV_NAME="${INFISICAL_ENV:-dev}"
GENERATED_ENV="secrets/infisical/agent-infra.generated.env"

usage() {
  cat <<'USAGE'
Usage: scripts/infisical/agent-infra-secrets.sh <generate|audit|push|export-template>

generate        Create/reuse local generated secrets in secrets/infisical/agent-infra.generated.env.
audit           Check which required secrets exist in Infisical and local environment without printing values.
push            Push generated/retrieved values to Infisical.
export-template Print a key/path manifest as CSV.
USAGE
}

rand_hex() {
  openssl rand -hex "${1:-32}"
}

rand_b64url() {
  openssl rand -base64 "${1:-48}" | tr '+/' '-_' | tr -d '=\n'
}

ensure_generated_file() {
  mkdir -p "$(dirname "$GENERATED_ENV")"
  chmod 700 "$(dirname "$GENERATED_ENV")"

  if [[ ! -f "$GENERATED_ENV" ]]; then
    umask 077
    cat >"$GENERATED_ENV" <<EOF
# Generated by scripts/infisical/agent-infra-secrets.sh.
# Do not commit.
PAPERCLIP_DB_PASSWORD=$(rand_b64url 36)
PAPERCLIP_SESSION_SECRET=$(rand_b64url 48)
SEARXNG_SECRET=$(rand_b64url 48)
BROWSERLESS_TOKEN=$(rand_b64url 36)
LETTA_DB_PASSWORD=$(rand_b64url 36)
LETTA_SERVER_PASSWORD=$(rand_b64url 48)
QDRANT_API_KEY=$(rand_b64url 36)
EOF
  fi

  chmod 600 "$GENERATED_ENV"
}

load_local_sources() {
  ensure_generated_file
  set -a
  # shellcheck disable=SC1090
  source "$GENERATED_ENV"
  for file in \
    infra/env/composio.env.example \
    infra/environments/voice-mesh.example.env \
    infra/environments/memory.example.env \
    infra/environments/oracle-agent-utils.example.env
  do
    [[ -f "$file" ]] || continue
    # Load only defaults for variables not already present.
    while IFS='=' read -r key value; do
      [[ "$key" =~ ^[A-Za-z_][A-Za-z0-9_]*$ ]] || continue
      [[ -n "${!key:-}" ]] && continue
      value="${value%%#*}"
      value="${value%$'\r'}"
      export "$key=$value"
    done < <(rg -N '^[A-Za-z_][A-Za-z0-9_]*=' "$file" || true)
  done
  set +a

  export COMPOSIO_DEFAULT_USER_ID="${COMPOSIO_DEFAULT_USER_ID:-nyra-system}"
  export COMPOSIO_MCP_TRANSPORT="${COMPOSIO_MCP_TRANSPORT:-streamable-http}"
  export COMPOSIO_MCP_SERVER_NAME="${COMPOSIO_MCP_SERVER_NAME:-composio}"
  export COMPOSIO_TOOLKITS_ALLOW="${COMPOSIO_TOOLKITS_ALLOW:-jira,slack,twenty}"
  export COMPOSIO_EXECUTION_POLICY="${COMPOSIO_EXECUTION_POLICY:-require-user-bound-connection}"
  export RTX3060_LAN_IP="${RTX3060_LAN_IP:-192.168.1.36}"
  export RTX3090TI_LAN_IP="${RTX3090TI_LAN_IP:-192.168.1.39}"
  export RTX5090_LAN_IP="${RTX5090_LAN_IP:-192.168.1.50}"
  export VOICE_PTP_INTERFACE="${VOICE_PTP_INTERFACE:-eno1}"
  export ASSISTANT_GATEWAY_URL="${ASSISTANT_GATEWAY_URL:-http://orchestrator.lan:3400}"
  export LITELLM_BASE_URL="${LITELLM_BASE_URL:-http://orchestrator.lan:4000/v1}"
  export MEMORY_BASE_URL="${MEMORY_BASE_URL:-http://oracle-vps.lan:5000}"

  if [[ -z "${LITELLM_API_KEY:-}" && -n "${LITELLM_MASTER_KEY:-}" ]]; then
    export LITELLM_API_KEY="$LITELLM_MASTER_KEY"
  fi
}

manifest_csv() {
  cat <<'CSV'
path,key,source,required
/oracle/agent-utils,PAPERCLIP_DB_PASSWORD,generated,yes
/oracle/agent-utils,PAPERCLIP_SESSION_SECRET,generated,yes
/oracle/agent-utils,SEARXNG_SECRET,generated,yes
/oracle/agent-utils,BROWSERLESS_TOKEN,generated,yes
/oracle/memory,LETTA_DB_PASSWORD,generated,yes
/oracle/memory,LETTA_SERVER_PASSWORD,generated,yes
/oracle/memory,QDRANT_API_KEY,generated,yes
/shared/providers,OPENAI_API_KEY,environment,yes
/shared/providers,ANTHROPIC_API_KEY,environment,no
/shared/providers,LITELLM_MASTER_KEY,environment,yes
/shared/composio,COMPOSIO_API_KEY,manual,yes
/shared/composio,COMPOSIO_MCP_SERVER_ID,manual,yes
/shared/composio,COMPOSIO_MCP_URL,manual,yes
/shared/composio,COMPOSIO_DEFAULT_USER_ID,config,yes
/shared/composio,COMPOSIO_MCP_TRANSPORT,config,yes
/shared/composio,COMPOSIO_MCP_SERVER_NAME,config,yes
/shared/composio,COMPOSIO_TOOLKITS_ALLOW,config,yes
/shared/composio,COMPOSIO_EXECUTION_POLICY,config,yes
/worker-rtx3060/voice,RTX3060_LAN_IP,config,yes
/worker-rtx3060/voice,RTX3090TI_LAN_IP,config,yes
/worker-rtx3060/voice,RTX5090_LAN_IP,config,yes
/worker-rtx3060/voice,VOICE_PTP_INTERFACE,config,yes
/worker-rtx3060/voice,ASSISTANT_GATEWAY_URL,config,yes
/worker-rtx3090ti/voice,RTX3060_LAN_IP,config,yes
/worker-rtx3090ti/voice,RTX3090TI_LAN_IP,config,yes
/worker-rtx3090ti/voice,RTX5090_LAN_IP,config,yes
/worker-rtx3090ti/voice,VOICE_PTP_INTERFACE,config,yes
/worker-rtx3090ti/voice,ASSISTANT_GATEWAY_URL,config,yes
/worker-rtx3090ti/voice,LITELLM_BASE_URL,config,yes
/worker-rtx3090ti/voice,LITELLM_API_KEY,environment,yes
/worker-rtx3090ti/voice,MEMORY_BASE_URL,config,yes
/worker-rtx3090ti/voice,COMPOSIO_API_KEY,manual,yes
/worker-rtx3090ti/voice,COMPOSIO_MCP_URL,manual,yes
/worker-rtx5090/voice,RTX3060_LAN_IP,config,yes
/worker-rtx5090/voice,RTX3090TI_LAN_IP,config,yes
/worker-rtx5090/voice,RTX5090_LAN_IP,config,yes
/worker-rtx5090/voice,VOICE_PTP_INTERFACE,config,yes
/worker-rtx5090/voice,ASSISTANT_GATEWAY_URL,config,yes
CSV
}

value_for_key() {
  local key="$1"
  printf '%s' "${!key:-}"
}

is_placeholder() {
  local value="$1"
  [[ -z "$value" || "$value" == replace-me || "$value" == replace-* || "$value" == *'${'* || "$value" == change-me* ]]
}

infisical_get_status() {
  local path="$1"
  local key="$2"
  local value
  value="$(infisical secrets get "$key" \
    --projectId "$PROJECT_ID" \
    --env "$INFISICAL_ENV_NAME" \
    --path "$path" \
    --plain \
    --silent 2>/dev/null || true)"
  if [[ -n "$value" ]]; then
    printf 'present'
  else
    printf 'missing'
  fi
}

set_secret() {
  local path="$1"
  local key="$2"
  local value="$3"
  infisical secrets set "$key=$value" \
    --projectId "$PROJECT_ID" \
    --env "$INFISICAL_ENV_NAME" \
    --path "$path" \
    --silent >/dev/null
}

audit() {
  load_local_sources
  printf 'Infisical project: %s\n' "$PROJECT_ID"
  printf 'Infisical env: %s\n' "$INFISICAL_ENV_NAME"
  printf '%-28s %-34s %-12s %-12s\n' "PATH" "KEY" "LOCAL" "INFISICAL"
  manifest_csv | tail -n +2 | while IFS=',' read -r path key source required; do
    value="$(value_for_key "$key")"
    if is_placeholder "$value"; then
      local_status="missing"
    else
      local_status="available"
    fi
    remote_status="$(infisical_get_status "$path" "$key")"
    printf '%-28s %-34s %-12s %-12s\n' "$path" "$key" "$local_status" "$remote_status"
  done
}

push() {
  load_local_sources
  local pushed=0
  local skipped=0

  manifest_csv | tail -n +2 | while IFS=',' read -r path key source required; do
    value="$(value_for_key "$key")"
    if is_placeholder "$value"; then
      printf 'skip %-34s missing local value\n' "$key"
      skipped=$((skipped + 1))
      continue
    fi
    set_secret "$path" "$key" "$value"
    printf 'set  %-34s %s\n' "$key" "$path"
    pushed=$((pushed + 1))
  done
}

cmd="${1:-}"
case "$cmd" in
  generate)
    ensure_generated_file
    printf 'generated/reused %s\n' "$GENERATED_ENV"
    ;;
  audit)
    audit
    ;;
  push)
    push
    ;;
  export-template)
    manifest_csv
    ;;
  *)
    usage
    exit 2
    ;;
esac
