#!/usr/bin/env bash
# Phase 1: Populate .env files with live Infisical secrets
# Usage: bash infra/scripts/phase1-populate-env.sh

set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

log() { echo -e "${BLUE}[PHASE1]${NC} $*"; }
ok() { echo -e "${GREEN}✓${NC} $*"; }
warn() { echo -e "${YELLOW}⚠${NC} $*"; }
err() { echo -e "${RED}✗${NC} $*"; exit 1; }

log "Phase 1: Populate .env Files"

# === Verify Infisical Access ===
log "Testing Infisical connectivity..."
if ! infisical secrets get LITELLM_MASTER_KEY --path /llm-providers/litellm >/dev/null 2>&1; then
    err "Cannot access Infisical. Check INFISICAL_TOKEN environment variable."
fi
ok "Infisical accessible"

# === Helper Function ===
get_secret() {
    local key=$1
    local path=$2
    infisical secrets get "$key" --path "$path" 2>/dev/null || echo "MISSING"
}

# === Phase 1 Required Secrets (with paths) ===
declare -A SECRETS=(
    # LiteLLM + upstreams
    [LITELLM_MASTER_KEY]="/llm-providers/litellm"
    [LITELLM_DATABASE_URL]="/llm-providers/litellm"
    [OPENROUTER_API_KEY]="/llm-providers/openrouter"
    [OMNIROUTE_API_KEY]="/llm-providers/litellm"
    [LLXPRT_BRIDGE_API_KEY]="/llm-providers/litellm"
    [ANTHROPIC_API_KEY]="/llm-providers/litellm"

    # Portainer
    [ORCHESTRATOR_PORTAINER_EDGE_ID]="/external/portainer"
    [ORCHESTRATOR_PORTAINER_EDGE_KEY]="/external/portainer"
    [WORKER_5090_PORTAINER_EDGE_ID]="/external/portainer"
    [WORKER_5090_PORTAINER_EDGE_KEY]="/external/portainer"

    # OpenClaw
    [OPENCLAW_GATEWAY_TOKEN]="/external/openclaw"

    # Tailscale
    [ORCHESTRATOR_TAILSCALE_AUTHKEY]="/external/tailscale"
    [WORKER_5090_TAILSCALE_AUTHKEY]="/external/tailscale"

    # Infisical bootstrap
    [INFISICAL_PROJECT_ID]="/security/infisical/local"
    [INFISICAL_TOKEN]="/security/infisical/local"
)

# === Populate Orchestrator .env ===
log "Populating orchestrator/.env..."
ORCH_ENV="infra/hosts/orchestrator/.env"
mkdir -p infra/hosts/orchestrator

cat > "$ORCH_ENV" << 'EOF'
# Orchestrator Phase 1 Bootstrap
# Generated by phase1-populate-env.sh — Do not commit
# chmod 600; gitignore active
COMPOSE_PROJECT_NAME=orchestrator
INFISICAL_PROJECT_ID=8374cea9-e5e8-4050-bda4-b91f25ab30ef
INFISICAL_ENV=prod
INFISICAL_PATH=/hosts/orchestrator
EOF

# Append live secrets (use --plain to get raw values without table formatting)
infisical secrets get INFISICAL_TOKEN --path /security/infisical/local --plain 2>/dev/null | sed 's/^/INFISICAL_TOKEN=/' >> "$ORCH_ENV" || warn "Could not fetch INFISICAL_TOKEN"
infisical secrets get LITELLM_MASTER_KEY --path /llm-providers/litellm --plain 2>/dev/null | sed 's/^/LITELLM_MASTER_KEY=/' >> "$ORCH_ENV"
infisical secrets get ORCHESTRATOR_PORTAINER_EDGE_ID --path /external/portainer --plain 2>/dev/null | sed 's/^/PORTAINER_EDGE_ID=/' >> "$ORCH_ENV"
infisical secrets get ORCHESTRATOR_PORTAINER_EDGE_KEY --path /external/portainer --plain 2>/dev/null | sed 's/^/PORTAINER_EDGE_KEY=/' >> "$ORCH_ENV"
infisical secrets get OPENCLAW_GATEWAY_TOKEN --path /external/openclaw --plain 2>/dev/null | sed 's/^/OPENCLAW_GATEWAY_TOKEN=/' >> "$ORCH_ENV"
infisical secrets get OMNIROUTE_API_KEY --path /llm-providers/litellm --plain 2>/dev/null | sed 's/^/OMNIROUTE_API_KEY=/' >> "$ORCH_ENV"
infisical secrets get LLXPRT_BRIDGE_API_KEY --path /llm-providers/litellm --plain 2>/dev/null | sed 's/^/LLXPRT_BRIDGE_API_KEY=/' >> "$ORCH_ENV"
infisical secrets get OPENROUTER_API_KEY --path /llm-providers/openrouter --plain 2>/dev/null | sed 's/^/OPENROUTER_API_KEY=/' >> "$ORCH_ENV"
infisical secrets get ANTHROPIC_API_KEY --path /llm-providers/litellm --plain 2>/dev/null | sed 's/^/ANTHROPIC_API_KEY=/' >> "$ORCH_ENV"

chmod 600 "$ORCH_ENV"
ok "Orchestrator .env populated ($(wc -l <"$ORCH_ENV") lines)"

# === Populate Worker-5090 .env ===
log "Populating worker-rtx5090/.env..."
WORKER_ENV="infra/hosts/worker-rtx5090/.env"
mkdir -p infra/hosts/worker-rtx5090

cat > "$WORKER_ENV" << 'EOF'
# Worker-RTX5090 Phase 1 Bootstrap
# Generated by phase1-populate-env.sh — Do not commit
# chmod 600; gitignore active
COMPOSE_PROJECT_NAME=worker-rtx5090
INFISICAL_PROJECT_ID=8374cea9-e5e8-4050-bda4-b91f25ab30ef
INFISICAL_ENV=prod
INFISICAL_PATH=/hosts/worker-rtx5090
EOF

# Append live secrets (use --plain to get raw values without table formatting)
infisical secrets get INFISICAL_TOKEN --path /security/infisical/local --plain 2>/dev/null | sed 's/^/INFISICAL_TOKEN=/' >> "$WORKER_ENV" || warn "Could not fetch INFISICAL_TOKEN"
infisical secrets get LITELLM_MASTER_KEY --path /llm-providers/litellm --plain 2>/dev/null | sed 's/^/LITELLM_MASTER_KEY=/' >> "$WORKER_ENV"
infisical secrets get WORKER_5090_PORTAINER_EDGE_ID --path /external/portainer --plain 2>/dev/null | sed 's/^/PORTAINER_EDGE_ID=/' >> "$WORKER_ENV"
infisical secrets get WORKER_5090_PORTAINER_EDGE_KEY --path /external/portainer --plain 2>/dev/null | sed 's/^/PORTAINER_EDGE_KEY=/' >> "$WORKER_ENV"
infisical secrets get WORKER_5090_TAILSCALE_AUTHKEY --path /external/tailscale --plain 2>/dev/null | sed 's/^/TAILSCALE_AUTHKEY=/' >> "$WORKER_ENV"

# vLLM config
echo "VLLM_MODEL=Qwen/Qwen3.8-27B" >> "$WORKER_ENV"
echo "VLLM_PORT=8000" >> "$WORKER_ENV"
echo "VLLM_GPU_MEMORY_UTILIZATION=0.85" >> "$WORKER_ENV"
echo "VLLM_MAX_MODEL_LEN=4096" >> "$WORKER_ENV"
echo "HF_TOKEN=" >> "$WORKER_ENV"  # Leave empty; vLLM can download public models

chmod 600 "$WORKER_ENV"
ok "Worker-5090 .env populated ($(wc -l <"$WORKER_ENV") lines)"

# === Verify Secrets Were Populated ===
log "Verifying secrets..."
missing=0

for secret in LITELLM_MASTER_KEY PORTAINER_EDGE_ID OPENCLAW_GATEWAY_TOKEN; do
    if grep -q "^${secret}=" "$ORCH_ENV"; then
        ok "orchestrator/.env :: $secret"
    else
        err "orchestrator/.env missing $secret"
        ((missing++))
    fi
done

for secret in LITELLM_MASTER_KEY PORTAINER_EDGE_ID TAILSCALE_AUTHKEY; do
    if grep -q "^${secret}=" "$WORKER_ENV"; then
        ok "worker-rtx5090/.env :: $secret"
    else
        err "worker-rtx5090/.env missing $secret"
        ((missing++))
    fi
done

if [ $missing -gt 0 ]; then
    err "$missing secrets missing from .env files"
fi

ok "All Phase 1 .env files populated successfully"
