#!/bin/bash

# Infisical Secrets Sync Service
# Continuously syncs secrets from Infisical to a shared volume

set -e

# Configuration
SYNC_INTERVAL=${SYNC_INTERVAL:-300}  # 5 minutes default
TARGET_ENV_FILE=${TARGET_ENV_FILE:-/app/shared/.env.synced}
SYNC_PORT=${SYNC_PORT:-8006}
LOG_FILE="/app/logs/sync.log"

# Ensure directories exist
mkdir -p /app/shared /app/logs

# Logging function
log() {
    echo "[$(date '+%Y-%m-%d %H:%M:%S')] $1" | tee -a "$LOG_FILE"
}

# Health check endpoint
start_health_server() {
    while true; do
        echo -e "HTTP/1.1 200 OK\r\n\r\nSecrets sync service running" | nc -l -p $SYNC_PORT -q 1
    done &
}

# Function to sync secrets
sync_secrets() {
    log "Starting secrets sync..."

    if [ -z "$INFISICAL_TOKEN" ]; then
        log "ERROR: INFISICAL_TOKEN not set"
        return 1
    fi

    if [ -z "$INFISICAL_PROJECT_ID" ]; then
        log "ERROR: INFISICAL_PROJECT_ID not set"
        return 1
    fi

    # Create temporary file
    TEMP_FILE=$(mktemp)

    # Export secrets from Infisical
    if infisical export --format=dotenv --token="$INFISICAL_TOKEN" --projectId="$INFISICAL_PROJECT_ID" > "$TEMP_FILE"; then
        # Add timestamp to the env file
        {
            echo "# Synced from Infisical at $(date)"
            echo "# DO NOT EDIT - This file is automatically generated"
            echo ""
            cat "$TEMP_FILE"
        } > "$TARGET_ENV_FILE"

        # Set proper permissions
        chmod 600 "$TARGET_ENV_FILE"

        log "Secrets synced successfully to $TARGET_ENV_FILE"

        # Clean up temp file
        rm -f "$TEMP_FILE"
        return 0
    else
        log "ERROR: Failed to sync secrets from Infisical"
        rm -f "$TEMP_FILE"
        return 1
    fi
}

# Signal handlers
cleanup() {
    log "Shutting down secrets sync service..."
    exit 0
}

trap cleanup SIGTERM SIGINT

# Main sync loop
log "Starting Infisical secrets sync service..."
log "Sync interval: $SYNC_INTERVAL seconds"
log "Target file: $TARGET_ENV_FILE"

# Start health check server
start_health_server

# Initial sync
sync_secrets

# Continuous sync loop
while true; do
    sleep "$SYNC_INTERVAL"
    sync_secrets
done