version: '3.8'

services:
  # Core MCP Services (Always Running)
  metamcp-core:
    image: metatool-ai/metamcp:latest
    container_name: nyra-metamcp-core
    ports:
      - "3000:3000"
    volumes:
      - ./configs:/configs
      - ../:/workspace
    environment:
      - CONFIG_FILE=/configs/metamcp-config.yaml
      - PORT=core-services
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - WORKSPACE_ROOT=/workspace
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Heavy Services (On-Demand)
  metamcp-heavy:
    image: metatool-ai/metamcp:latest
    container_name: nyra-metamcp-heavy
    ports:
      - "3001:3001"
    volumes:
      - ./configs:/configs
      - ../:/workspace
    environment:
      - CONFIG_FILE=/configs/metamcp-config.yaml
      - PORT=heavy-services
      - WORKSPACE_ROOT=/workspace
    profiles:
      - heavy
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 2G

  # Development Tools
  metamcp-dev:
    image: metatool-ai/metamcp:latest
    container_name: nyra-metamcp-dev
    ports:
      - "3002:3002"
    volumes:
      - ./configs:/configs
      - ../:/workspace
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONFIG_FILE=/configs/metamcp-config.yaml
      - PORT=dev-tools
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY}
      - WORKSPACE_ROOT=/workspace
    restart: unless-stopped

  # Optional Services
  metamcp-optional:
    image: metatool-ai/metamcp:latest
    container_name: nyra-metamcp-optional
    ports:
      - "3003:3003"
    volumes:
      - ./configs:/configs
      - ../:/workspace
    environment:
      - CONFIG_FILE=/configs/metamcp-config.yaml
      - PORT=optional-services
      - NOTION_TOKEN=${NOTION_TOKEN}
      - QDRANT_URL=${QDRANT_URL}
      - QDRANT_API_KEY=${QDRANT_API_KEY}
      - WORKSPACE_ROOT=/workspace
    profiles:
      - optional

networks:
  default:
    name: nyra-mcp-network