// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/integrations" | "/applications" | "/assistant" | "/campaigns" | "/campaigns/[id]" | "/campaigns/builder" | "/campaigns/builder/[id]" | "/crm" | "/crm/settings" | "/fleet" | "/fleet/[nodeId]" | "/leads" | "/leads/[id]" | "/memory" | "/nexus" | "/pipeline" | "/quotes" | "/quotes/[id]" | "/settings" | "/tools/activepieces" | "/tools/n8n" | "/tools/nexus" | "/tools/openclaw" | "/tools/openmemory" | "/tools/paperclip"
type AppRouteHandlerRoutes = "/api/applications" | "/api/campaigns" | "/api/campaigns/[id]" | "/api/crm" | "/api/dashboard/pipeline" | "/api/internal/fleet/status" | "/api/internal/openclaw/chat" | "/api/internal/openclaw/health" | "/api/leads" | "/api/leads/[id]" | "/api/leads/[id]/campaign" | "/api/leads/[id]/conversation" | "/api/memory/actions/merge" | "/api/memory/actions/rebuild" | "/api/memory/graph" | "/api/memory/overview" | "/api/quote/[loanType]" | "/api/quote/compare-loan-types" | "/api/quote/loan-types" | "/api/quotes/[id]" | "/api/quotes/[id]/approve" | "/api/quotes/generate" | "/api/settings" | "/api/status"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/integrations": {}
  "/api/applications": {}
  "/api/campaigns": {}
  "/api/campaigns/[id]": { "id": string; }
  "/api/crm": {}
  "/api/dashboard/pipeline": {}
  "/api/internal/fleet/status": {}
  "/api/internal/openclaw/chat": {}
  "/api/internal/openclaw/health": {}
  "/api/leads": {}
  "/api/leads/[id]": { "id": string; }
  "/api/leads/[id]/campaign": { "id": string; }
  "/api/leads/[id]/conversation": { "id": string; }
  "/api/memory/actions/merge": {}
  "/api/memory/actions/rebuild": {}
  "/api/memory/graph": {}
  "/api/memory/overview": {}
  "/api/quote/[loanType]": { "loanType": string; }
  "/api/quote/compare-loan-types": {}
  "/api/quote/loan-types": {}
  "/api/quotes/[id]": { "id": string; }
  "/api/quotes/[id]/approve": { "id": string; }
  "/api/quotes/generate": {}
  "/api/settings": {}
  "/api/status": {}
  "/applications": {}
  "/assistant": {}
  "/campaigns": {}
  "/campaigns/[id]": { "id": string; }
  "/campaigns/builder": {}
  "/campaigns/builder/[id]": { "id": string; }
  "/crm": {}
  "/crm/settings": {}
  "/fleet": {}
  "/fleet/[nodeId]": { "nodeId": string; }
  "/leads": {}
  "/leads/[id]": { "id": string; }
  "/memory": {}
  "/nexus": {}
  "/pipeline": {}
  "/quotes": {}
  "/quotes/[id]": { "id": string; }
  "/settings": {}
  "/tools/activepieces": {}
  "/tools/n8n": {}
  "/tools/nexus": {}
  "/tools/openclaw": {}
  "/tools/openmemory": {}
  "/tools/paperclip": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
