// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/(broker)/applications/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/applications">> = Specific
  const handler = {} as typeof import("../../app/(broker)/applications/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/assistant/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/assistant">> = Specific
  const handler = {} as typeof import("../../app/(broker)/assistant/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/campaigns/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../app/(broker)/campaigns/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/campaigns/builder/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/builder/[id]">> = Specific
  const handler = {} as typeof import("../../app/(broker)/campaigns/builder/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/campaigns/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns/builder">> = Specific
  const handler = {} as typeof import("../../app/(broker)/campaigns/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/campaigns/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/campaigns">> = Specific
  const handler = {} as typeof import("../../app/(broker)/campaigns/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/leads/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/(broker)/leads/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/leads/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leads">> = Specific
  const handler = {} as typeof import("../../app/(broker)/leads/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/pipeline/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/pipeline">> = Specific
  const handler = {} as typeof import("../../app/(broker)/pipeline/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/quotes/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../app/(broker)/quotes/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(broker)/quotes/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/quotes">> = Specific
  const handler = {} as typeof import("../../app/(broker)/quotes/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/admin/integrations/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/integrations">> = Specific
  const handler = {} as typeof import("../../app/(ops)/admin/integrations/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/(ops)/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/crm/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm">> = Specific
  const handler = {} as typeof import("../../app/(ops)/crm/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/crm/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/crm/settings">> = Specific
  const handler = {} as typeof import("../../app/(ops)/crm/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/fleet/[nodeId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fleet/[nodeId]">> = Specific
  const handler = {} as typeof import("../../app/(ops)/fleet/[nodeId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/fleet/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/fleet">> = Specific
  const handler = {} as typeof import("../../app/(ops)/fleet/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/memory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/memory">> = Specific
  const handler = {} as typeof import("../../app/(ops)/memory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/nexus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/nexus">> = Specific
  const handler = {} as typeof import("../../app/(ops)/nexus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(ops)/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/(ops)/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/activepieces/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/activepieces">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/activepieces/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/n8n/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/n8n">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/n8n/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/nexus/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/nexus">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/nexus/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/openclaw/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/openclaw">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/openclaw/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/openmemory/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/openmemory">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/openmemory/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/(tools)/tools/paperclip/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tools/paperclip">> = Specific
  const handler = {} as typeof import("../../app/(tools)/tools/paperclip/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/applications/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/applications">> = Specific
  const handler = {} as typeof import("../../app/api/applications/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/campaigns/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/campaigns">> = Specific
  const handler = {} as typeof import("../../app/api/campaigns/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/crm/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/crm">> = Specific
  const handler = {} as typeof import("../../app/api/crm/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/dashboard/pipeline/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/dashboard/pipeline">> = Specific
  const handler = {} as typeof import("../../app/api/dashboard/pipeline/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/internal/fleet/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/fleet/status">> = Specific
  const handler = {} as typeof import("../../app/api/internal/fleet/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/internal/openclaw/chat/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/openclaw/chat">> = Specific
  const handler = {} as typeof import("../../app/api/internal/openclaw/chat/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/internal/openclaw/health/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/internal/openclaw/health">> = Specific
  const handler = {} as typeof import("../../app/api/internal/openclaw/health/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/[id]/campaign/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/campaign">> = Specific
  const handler = {} as typeof import("../../app/api/leads/[id]/campaign/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/[id]/conversation/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]/conversation">> = Specific
  const handler = {} as typeof import("../../app/api/leads/[id]/conversation/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/leads/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leads/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leads">> = Specific
  const handler = {} as typeof import("../../app/api/leads/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/actions/merge/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/actions/merge">> = Specific
  const handler = {} as typeof import("../../app/api/memory/actions/merge/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/actions/rebuild/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/actions/rebuild">> = Specific
  const handler = {} as typeof import("../../app/api/memory/actions/rebuild/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/graph/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/graph">> = Specific
  const handler = {} as typeof import("../../app/api/memory/graph/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/memory/overview/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/memory/overview">> = Specific
  const handler = {} as typeof import("../../app/api/memory/overview/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quote/[loanType]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote/[loanType]">> = Specific
  const handler = {} as typeof import("../../app/api/quote/[loanType]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quote/compare-loan-types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote/compare-loan-types">> = Specific
  const handler = {} as typeof import("../../app/api/quote/compare-loan-types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quote/loan-types/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quote/loan-types">> = Specific
  const handler = {} as typeof import("../../app/api/quote/loan-types/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quotes/[id]/approve/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]/approve">> = Specific
  const handler = {} as typeof import("../../app/api/quotes/[id]/approve/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quotes/[id]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/[id]">> = Specific
  const handler = {} as typeof import("../../app/api/quotes/[id]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/quotes/generate/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/quotes/generate">> = Specific
  const handler = {} as typeof import("../../app/api/quotes/generate/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/settings/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/settings">> = Specific
  const handler = {} as typeof import("../../app/api/settings/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/status/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/status">> = Specific
  const handler = {} as typeof import("../../app/api/status/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
