model_list:
  - model_name: llxpert-coder
    litellm_params:
      model: openai/llxpert-coder
      api_base: os.environ/LLXPERT_CODER_BASE_URL
      api_key: os.environ/LLXPERT_CODER_API_KEY

  - model_name: llxpert-jefe
    litellm_params:
      model: openai/llxpert-jefe
      api_base: os.environ/LLXPERT_JEFE_BASE_URL
      api_key: os.environ/LLXPERT_JEFE_API_KEY

  - model_name: openrouter/auto
    litellm_params:
      model: openrouter/auto
      api_key: os.environ/OPENROUTER_API_KEY
      api_base: https://openrouter.ai/api/v1

general_settings:
  master_key: sk-local-dev
