services:
  nexus:
    image: ghcr.io/grafbase/nexus:stable
    container_name: nexus
    env_file:
      - .env
    environment:
      - NEXUS_CONFIG_PATH=/etc/nexus/nexus.toml
      - NEXUS_LOG=${NEXUS_LOG:-info}
    ports:
      - "8000:8000"
    volumes:
      - ./config/nexus.toml:/etc/nexus/nexus.toml:ro
