# Pulls secrets from Infisical and writes:
#   .secrets/shared.env
#   .secrets/project-nyra.env
#   .secrets/gemini-flow.env
# Then composes a top-level .env (shared first, then project, then gemini override)

param(
  [string]$ProjectId = "8374cea9-e5e8-4050-bda4-b91f25ab30ef",
  [string]$Env = "dev"
)

$ErrorActionPreference = "Stop"
$Root = (Get-Location).Path
$OutDir = Join-Path $Root ".secrets"
if (!(Test-Path $OutDir)) { New-Item -ItemType Directory -Path $OutDir | Out-Null }

function Export-Path([string]$InfPath, [string]$OutFile){
  Write-Host ">> Exporting $InfPath -> $OutFile" -ForegroundColor Cyan
  infisical export --projectId=$ProjectId --env=$Env --path=$InfPath --format=dotenv | Out-File -Encoding ascii -FilePath $OutFile
}

Export-Path "/shared"       (Join-Path $OutDir "shared.env")
Export-Path "/project-nyra" (Join-Path $OutDir "project-nyra.env")
Export-Path "/gemini-flow"  (Join-Path $OutDir "gemini-flow.env")

# Compose .env (priority: shared < project-nyra < gemini-flow)
$EnvOut = Join-Path $Root ".env"
Write-Host ">> Composing $EnvOut" -ForegroundColor Cyan
@"
# GENERATED by scripts/secrets/pull-dotenv.ps1
# Order: shared < project-nyra < gemini-flow (later wins)
"@ | Out-File -Encoding ascii $EnvOut

Get-Content (Join-Path $OutDir "shared.env")       | Where-Object {$_ -notmatch "^\s*#"} | Out-File -Append -Encoding ascii $EnvOut
Get-Content (Join-Path $OutDir "project-nyra.env") | Where-Object {$_ -notmatch "^\s*#"} | Out-File -Append -Encoding ascii $EnvOut
Get-Content (Join-Path $OutDir "gemini-flow.env")  | Where-Object {$_ -notmatch "^\s*#"} | Out-File -Append -Encoding ascii $EnvOut

Write-Host ">> Done. .env and .secrets/*.env are ready (git-ignored)."
