#!/bin/bash
# Project Nyra GPU Mesh - Quick Start Guide
set -e

echo "🚀 Project Nyra GPU Mesh Setup"
echo "=============================="
echo ""
echo "📋 Current Status:"
echo "✅ LiteLLM config updated with GPU workers (vLLM + Ollama)"
echo "✅ Nexus Router config updated with worker endpoints"
echo "✅ Docker Compose files ready for all workers"
echo ""

echo "🖥️ Worker Configuration:"
echo "1️⃣  RTX 5090 (100.64.0.10) → vLLM + LMCache → Personal Assistant (Gemma 4/27B)"
echo "2️⃣  RTX 3090 Ti (100.64.0.12) → vLLM + LMCache → Coding (Qwen 3.5/32B)"
echo "3️⃣  RTX 3060 (100.64.0.11) → Ollama → Small models & Embeddings"
echo ""

echo "🔧 Commands to Run:"
echo ""
echo "1️⃣  On Orchestrator (restart Nexus + LiteLLM):"
echo "   cd ~/repos/project-nyra"
echo "   docker compose -f docker-compose.archon.yml restart nexus-router litellm"
echo ""

echo "2️⃣  On RTX 5090 Worker (100.64.0.10):"
echo "   cd ~/repos/project-nyra/infra/workers/worker-rtx5090"
echo "   docker compose -f docker-compose.gpu.yml --profile gpu up -d"
echo ""

echo "3️⃣  On RTX 3090 Ti Worker (100.64.0.12):"
echo "   cd ~/repos/project-nyra/infra/workers/worker-rtx3090ti"
echo "   docker compose -f docker-compose.gpu.yml --profile gpu up -d"
echo ""

echo "4️⃣  On RTX 3060 Worker (100.64.0.11):"
echo "   cd ~/repos/project-nyra/infra/workers/worker-rtx3060"
echo "   docker compose -f docker-compose.gpu.yml --profile gpu up -d"
echo "   # After Ollama starts, load models:"
echo "   docker compose -f docker-compose.gpu.yml --profile setup up ollama-model-loader"
echo ""

echo "✅ Test Commands:"
echo "# Check LiteLLM routing:"
echo "curl http://localhost:4000/v1/models | jq '.data[] | select(.id | startswith(\"local/\"))'"
echo ""
echo "# Test RTX5090 directly:"
echo "curl http://100.64.0.10:8000/v1/models"
echo ""
echo "# Test RTX3090 Ti directly:"
echo "curl http://100.64.0.12:8000/v1/models"
echo ""

echo "🎯 Local Model Registry:"
echo "• local/gemma-4 → RTX5090"
echo "• local/vybestack-jefe → RTX5090"
echo "• local/qwen3.5-35b-a3b → RTX3090 Ti"
echo "• local/vybestack-coder → RTX3090 Ti"
echo "• local/qwen2.5-4b → RTX3060"
echo ""
