version: "3.9"

name: nyra-memory

networks:
  nyra-net:
    driver: bridge

volumes:
  qdrant_data:
  neo4j_data:
  neo4j_logs:
  metamcp_pg:
  openwebui_data:

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:latest
    restart: unless-stopped
    ports: ["3000:8080"]
    volumes: [ "openwebui_data:/app/backend/data" ]
    networks: [nyra-net]

  qdrant:
    image: qdrant/qdrant:latest
    restart: unless-stopped
    ports: ["6333:6333","6334:6334"]
    volumes: [ "qdrant_data:/qdrant/storage" ]
    networks: [nyra-net]

  neo4j:
    image: neo4j:5-community
    restart: unless-stopped
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD:-neo4j-password}
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_PLUGINS=["apoc"]
    ports: ["7474:7474","7687:7687"]
    volumes: [ "neo4j_data:/data", "neo4j_logs:/logs" ]
    networks: [nyra-net]

  graphiti-mcp:
    image: ghcr.io/getzep/graphiti-mcp:latest
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - MODEL_NAME=${MODEL_NAME:-gpt-4o-mini}
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=${NEO4J_PASSWORD:-neo4j-password}
      - GRAPHITI_TRANSPORT=sse
      - GRAPHITI_PORT=8000
    depends_on: [neo4j]
    ports: ["7459:8000"]
    networks: [nyra-net]

  qdrant-mcp:
    image: ghcr.io/qdrant/mcp-server-qdrant:latest
    restart: unless-stopped
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=${QDRANT_COLLECTION:-nyra}
      - EMBEDDING_PROVIDER=fastembed
      - EMBEDDING_MODEL=sentence-transformers/all-MiniLM-L6-v2
      - FASTMCP_PORT=8066
      - FASTMCP_HOST=0.0.0.0
    depends_on: [qdrant]
    ports: ["8066:8066"]
    networks: [nyra-net]

  openmemory:
    image: ghcr.io/mem0ai/openmemory:latest
    restart: unless-stopped
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEXT_PUBLIC_API_URL=http://localhost:8765
      - NEXT_PUBLIC_USER_ID=${OPENMEMORY_USER:-nyra}
      - USER=${OPENMEMORY_USER:-nyra}
    ports: ["8765:8765","3000:3000"]
    networks: [nyra-net]

  metamcp:
    image: ghcr.io/metatool-ai/metamcp:latest
    restart: unless-stopped
    env_file: [ "../deployment/metamcp/.env" ]
    volumes:
      - metamcp_pg:/var/lib/postgresql/data
      - ../deployment/metamcp/servers.json:/app/servers.json:ro
      - ../deployment/metamcp/namespaces.json:/app/namespaces.json:ro
      - ../deployment/metamcp/endpoints.json:/app/endpoints.json:ro
    ports: ["12008:12008","12005:12005"]
    networks: [nyra-net]
