alias ls='eza --icons --group-directories-first --color=always'
alias ll='eza -lh --icons --group-directories-first --color=always'
alias la='eza -lha --icons --group-directories-first --color=always'
alias dl='aria2c -x16 -s16 -k1M -c'
alias cx='chmod +x'
alias nyra='cd ~/repos/project-nyra'
alias infis='infisical run --projectId="${INFISICAL_PROJECT_ID:-}" --env="${INFISICAL_ENV:-dev}" --path="${INFISICAL_FOLDER_PATH:-/shared}" -- '
alias claude-yolo='claude --dangerously-skip-permissions'
alias warp='warp.exe .'
alias agy='antigravity.exe .'
alias antigravity='antigravity.exe .'
alias subl='subl.exe .'
alias sg='sourcegit'
alias ipconfig='ip a'
alias ifconfig='ip a'

export WIN_HOME="/mnt/c/Users/$(cmd.exe /c echo %USERNAME% 2>/dev/null | tr -d $'\r')"
alias winhome='cd "$WIN_HOME"'

alias d-orch='docker --context default'
alias d-3060='docker --context worker-rtx3060'
alias d-3090='docker --context worker-rtx3090ti'
alias d-5090='docker --context worker-rtx5090'
alias nyra-ps='for c in default worker-rtx3060 worker-rtx3090ti worker-rtx5090; do echo "--- Context: $c ---"; docker --context $c ps --format "table {{.Names}}\t{{.Status}}\t{{.Ports}}"; done'
alias claude-local='claude-code --api-base http://localhost:4000/v1 --model local/vybestack-coder'
