#!/bin/bash
# Setup Infisical secrets for Docker Hub MCP Server
# Usage: ./scripts/setup-infisical.sh

set -e

echo "🔐 Docker Hub MCP - Infisical Setup"
echo "===================================="
echo

# Check if Infisical CLI is installed
if ! command -v infisical &> /dev/null; then
    echo "❌ Infisical CLI not found. Please install it first:"
    echo "   https://infisical.com/docs/cli/overview"
    exit 1
fi

# Check if logged in
if ! infisical whoami &> /dev/null; then
    echo "📝 Please log in to Infisical first:"
    infisical login
fi

echo "✅ Infisical CLI is ready"
echo

# Prompt for configuration
read -p "Enter your Infisical Project ID: " PROJECT_ID
read -p "Enter Docker Hub username: " DOCKERHUB_USERNAME
read -sp "Enter Docker Hub access token: " DOCKERHUB_TOKEN
echo
read -p "Enter Docker Hub namespace [default: $DOCKERHUB_USERNAME]: " DOCKERHUB_NAMESPACE
DOCKERHUB_NAMESPACE=${DOCKERHUB_NAMESPACE:-$DOCKERHUB_USERNAME}

echo
echo "📦 Setting up secrets in path: /nyra/dockerhub"
echo

# Set secrets in Infisical
infisical secrets set DOCKERHUB_USERNAME "$DOCKERHUB_USERNAME" \
    --projectId "$PROJECT_ID" \
    --env production \
    --path /nyra/dockerhub

infisical secrets set DOCKERHUB_TOKEN "$DOCKERHUB_TOKEN" \
    --projectId "$PROJECT_ID" \
    --env production \
    --path /nyra/dockerhub

infisical secrets set DOCKERHUB_NAMESPACE "$DOCKERHUB_NAMESPACE" \
    --projectId "$PROJECT_ID" \
    --env production \
    --path /nyra/dockerhub

echo
echo "✅ Secrets configured successfully!"
echo

# Create service token
echo "🔑 Creating service token for MCP server..."
TOKEN=$(infisical service-token create \
    --name "dockerhub-mcp-$(date +%Y%m%d)" \
    --projectId "$PROJECT_ID" \
    --env production \
    --path /nyra/dockerhub \
    --format json | jq -r '.serviceToken')

echo
echo "📋 Configuration Summary"
echo "========================"
echo "Project ID:      $PROJECT_ID"
echo "Username:        $DOCKERHUB_USERNAME"
echo "Namespace:       $DOCKERHUB_NAMESPACE"
echo "Service Token:   ${TOKEN:0:20}..." # Show only first 20 chars
echo

# Save to .env file
cat > ../.env << EOF
# Docker Hub MCP Server - Auto-generated by setup-infisical.sh
# Generated: $(date)

# Infisical Configuration
INFISICAL_PROJECT_ID=$PROJECT_ID
INFISICAL_TOKEN=$TOKEN

# Docker Hub Configuration
DOCKERHUB_USERNAME=$DOCKERHUB_USERNAME
DOCKERHUB_NAMESPACE=$DOCKERHUB_NAMESPACE

# Service Configuration
MCP_PORT=8007
NYRA_ENVIRONMENT=production
NYRA_PC_ID=orchestrator
LOG_LEVEL=info
CACHE_TTL=300
RATE_LIMIT=100
EOF

echo "💾 Configuration saved to .env"
echo
echo "🚀 Next steps:"
echo "   1. Review the generated .env file"
echo "   2. Start the service: docker-compose -f docker-compose.dockerhub-mcp.yml up -d"
echo "   3. Check health: curl http://localhost:8007/health"
echo
echo "✨ Setup complete!"
