name: Dependency Security Scan

on:
  schedule:
    - cron: '0 0 * * 0'  # weekly, every Sunday at midnight UTC
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Python Security Audit
        run: |
          pip install pip-audit
          pip-audit
