version: '3.9'

networks:
  nyra:
    external: true

volumes:
  portainer_data: {}

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: nyra-portainer
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
    networks: [nyra]

  dozzle:
    image: amir20/dozzle:latest
    container_name: nyra-dozzle
    ports:
      - '9999:8080'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    networks: [nyra]
